# Generated by Django 5.0 on 2023-12-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('production', 'Production'), ('staging', 'Staging')], default='staging', max_length=100),
        ),
    ]
