# Generated by Django 4.2.9 on 2024-01-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_aboutmesections"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="language",
            field=models.CharField(
                choices=[("en", "english"), ("uz", "uzbek")],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="aboutmesections",
            name="language",
            field=models.CharField(
                choices=[("en", "english"), ("uz", "uzbek")],
                default="en",
                max_length=10,
            ),
        ),
    ]
