# Generated by Django 4.2.9 on 2024-01-04 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_and_aboutmesections_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutmesections",
            name="alternative",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.aboutmesections",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="alternative",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.post",
            ),
        ),
    ]
