# Generated by Django 5.0 on 2024-01-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_aboutmesections'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmesections',
            name='status',
            field=models.CharField(choices=[('production', 'Production'), ('staging', 'Staging')], default='staging', max_length=20),
        ),
    ]
