# Generated by Django 4.2.9 on 2024-01-07 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutmesections",
            name="title",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
    ]
